In [1]:
#dependencies
import time
import pandas as pd
import json as json
import csv
import numpy as np

In [5]:
plates = pd.read_csv("plates.csv", encoding = "utf-8")
plates.head()

,SeqNum,PlateBoundIdentifer,PlateBoundContinuity,StartLong,StartLat,FinalLong,FinalLat,StepLength(km),AzimuthCenter,VelocityLeft,VelocityAzimuth,VelocityDivergent,VelocityRightLateral,Elevation,SeafloorAge,StepClass,StepContinuity,Orogen
0,1,AF-AN,False,-0.438,-54.852,-0.039,-54.677,32.1,53,13.2,48,1.2,13.1,-1584,2,OTF,False,False
1,2,AF-AN,True,-0.039,-54.677,0.443,-54.451,40.0,51,13.2,47,0.9,13.1,-1639,5,OTF,True,False
2,3,AF-AN,True,0.443,-54.451,0.965,-54.832,54.0,142,13.2,47,13.1,-1.1,-1687,4,OSR,False,False
3,4,AF-AN,True,0.965,-54.832,1.695,-54.399,67.3,44,13.2,46,-0.4,13.2,-4289,1,OTF,False,False
4,5,AF-AN,True,1.695,-54.399,2.360,-54.037,59.0,47,13.2,45,0.4,13.2,-4517,2,OTF,True,False

In [31]:
plate_names_not_clean = plates["PlateBoundIdentifer"].unique()
plate_names = list(plate_names_not_clean)
plate_names[0:3]

['AF-AN', 'AN-AF', 'SO-AN']

In [17]:
plates_lat_longs = plates[["PlateBoundIdentifer", "StartLat", "StartLong"]]
plates_lat_longs.head()

  PlateBoundIdentifer  StartLat  StartLong
0               AF-AN   -54.852     -0.438
1               AF-AN   -54.677     -0.039
2               AF-AN   -54.451      0.443
3               AF-AN   -54.832      0.965
4               AF-AN   -54.399      1.695

In [56]:
plate_dict = {}
for plate in plate_names:
    plate_dict_list = []
    plate_actual_dict = {}
    plate_dict_list.append(plate)
    lat_long_list = []
    for index, row in plates_lat_longs.iterrows():
        plate_name = row["PlateBoundIdentifer"]
        if plate_name == plate:
            lat_long_list.append([row["StartLat"], row["StartLong"]])
    plate_dict_list.append(lat_long_list)
    plate_dict[plate] = lat_long_list
    #dict_list.append(plate_actual_dict)
    #for item in plate_dict_list:
     #   print(item)
#plate_actual_dict['AN-AF']

In [58]:
to_json(plate_dict)

NameError: name 'to_json' is not defined